apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: io-delay-example
spec:
  action: latency
  mode: one
  path: "/var/run/etcd/**/*"
  selector:
    labelSelectors:
      app: etcd
  volumePath: /var/run/etcd
  delay: "20ms"
  percent: 10
