// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by chaos-multiversion-helper. DO NOT EDIT.

package v1alpha2

func (*AWSChaos) Hub() {}

func (*BlockChaos) Hub() {}

func (*DNSChaos) Hub() {}

func (*GCPChaos) Hub() {}

func (*HTTPChaos) Hub() {}

func (*IOChaos) Hub() {}

func (*JVMChaos) Hub() {}

func (*KernelChaos) Hub() {}

func (*NetworkChaos) Hub() {}

func (*PhysicalMachineChaos) Hub() {}

func (*PhysicalMachine) Hub() {}

func (*PhysicalMachineList) Hub() {}

func (*PodChaos) Hub() {}

func (*PodHttpChaosList) Hub() {}

func (*PodHttpChaos) Hub() {}

func (*PodIOChaos) Hub() {}

func (*PodIOChaosList) Hub() {}

func (*PodNetworkChaos) Hub() {}

func (*PodNetworkChaosList) Hub() {}

func (*Schedule) Hub() {}

func (*ScheduleList) Hub() {}

func (*StressChaos) Hub() {}

func (*TimeChaos) Hub() {}

func (*Workflow) Hub() {}

func (*WorkflowList) Hub() {}

func (*WorkflowNode) Hub() {}

func (*WorkflowNodeList) Hub() {}

func (*KernelChaosList) Hub() {}

func (*DNSChaosList) Hub() {}

func (*GCPChaosList) Hub() {}

func (*StressChaosList) Hub() {}

func (*PodChaosList) Hub() {}

func (*AWSChaosList) Hub() {}

func (*TimeChaosList) Hub() {}

func (*PhysicalMachineChaosList) Hub() {}

func (*IOChaosList) Hub() {}

func (*BlockChaosList) Hub() {}

func (*HTTPChaosList) Hub() {}

func (*JVMChaosList) Hub() {}

func (*NetworkChaosList) Hub() {}
